### ISSUE TITLE
error / debug message

### ISSUE THREAD

**Issue by Daeveren** [chancedj/LockedOut#103]
Using 1.7 beta, these are shown in chat at login and also everytime I mouseover LockedOut
![2018-01-28 16_48_13-world of warcraft](https://user-images.githubusercontent.com/6321337/35483478-3266952a-044b-11e8-80a2-00bdbdc6222b.jpg)

**Comment by chancedj** [comment]
thanks.  i'll have to see whats going on.  It would appear those instances are either a) in the encounter journal under a different name OR they are not there at all.

**Comment by chancedj** [comment]
yup.

Coilfang: The Underbog is listed as the underbog in the encounter journal.
Coilfan: Serpentshrine Cavern is listed as Serpentshrine Cavern in the encounter journal

etc

Seems the assumption that at LEAST he name of the stupid dungeons matched what was in the EJ would be good, but yet again blizzard lets me down.

**Comment by chancedj** [comment]
ok - after some research ive found a fix for this i think.  i'll use the localization strings for the name inside blizzards code.  it will require some hard coding - but at least i'll have it all correct.

**Comment by chancedj** [comment]
removed the localization.  this should be gone now.
