### ISSUE TITLE
error in 1.7

### ISSUE THREAD

**Issue by Daeveren** [chancedj/LockedOut#104]
getting this error like crazy, everywhere

Message: Interface\AddOns\LockedOut\Instances.lua:186: attempt to index field '?' (a nil value)
Time: 02/03/18 14:43:33
Count: 38
Stack: Interface\AddOns\LockedOut\Instances.lua:186: attempt to index field '?' (a nil value)
Interface\SharedXML\SharedBasicControls.lua:208: in function `origErrorHandler'
...ce\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:645: in function <...ce\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:607>
(tail call): ?
Interface\AddOns\LockedOut\Instances.lua:186: in function <Interface\AddOns\LockedOut\Instances.lua:175>
Interface\AddOns\LockedOut\Instances.lua:288: in function `Lockedout_BuildInstanceLockout'
Interface\AddOns\LockedOut\Character.lua:154: in function `Lockedout_GetCurrentCharData'
Interface\AddOns\LockedOut\Configuration.lua:766: in function `?'
...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:145: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:145>
[string "safecall Dispatcher[2]"]:4: in function <[string "safecall Dispatcher[2]"]:4>
[C]: ?
[string "safecall Dispatcher[2]"]:13: in function `?'
...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: in function `Fire'
Interface\AddOns\Ace3\AceEvent-3.0\AceEvent-3.0.lua:120: in function <Interface\AddOns\Ace3\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>

**Comment by chancedj** [comment]
thanks.  i'm going to have to back out the localization of bosses and instances.  it's just going to prove to be too problematic to build properly unfortunately.  once i rip that out it will correct this error.  i'll leave it for the time being...

**Comment by chancedj** [comment]
fixed with newest commit
