### ISSUE TITLE
time played not shown

### ISSUE THREAD

**Issue by Daeveren** [chancedj/LockedOut#105]
It's just empty on all the chars.
Also maybe the tooltip (this small one) can be made matte - as seen in the screenshot, the text mixes with the one beneath it

![2018-02-03 21_26_23-world of warcraft](https://user-images.githubusercontent.com/6321337/35770733-68545d10-0929-11e8-8277-923ad19cd2d8.jpg)

**Comment by chancedj** [comment]
yea.  i noticed this too.  it's only on the far left and only when it overlaps the titles on the side.  need to see why it happens

**Comment by chancedj** [comment]
fixed!
