### ISSUE TITLE
Please add daily heroic dungeon (for essences) tracker

### ISSUE THREAD

**Issue by magocchi** [chancedj/LockedOut#106]
I like to do the daily heroic on all my toons for waking essences, but never remember who I already did it on or not lol
Also this feels like it would already be in there, but I couldn't find it at all and didn't get an answer on discord either :(

**Comment by Daeveren** [comment]
Technically the addon tracks your dungeons, so you can see at a glance on which of your chars you've completed a Legion heroic. But afaik, it doesn't track the daily quest that counts as 'first daily heroic'.

**Comment by magocchi** [comment]
it doesn't seem to track any dungeons for me unless I queue for "specific dungeon". does it track it for you if you queue for random? in that case I might have to reinstall it lol

**Comment by chancedj** [comment]
thanks.  i'll check into this one.

**Comment by Daeveren** [comment]
Oh right, I think I know what it is. I don't do current expansion dungeons at all (only old ones for mounts/pets/transmog), but in a way it's logical that it doesn't track it - because doing random LFD does **not** result in a lock out, you're not saved to that dungeon - as opposed to queuing specifically for that dungeon, at which point you're saved, hence being limited to a 1 day save/reset.
Maybe @chancedj would add "daily heroic dungeon" to the tracked things of the addon - but it won't show which dungeon you've done, since there's no associated save with it (just the daily quest flagged as done).

**Comment by magocchi** [comment]
Yea that's a good point thanks Daeveren :) 
but yea personally, I don't care which dungeon it is, just wanna see if I got the bonus for the first one of the day.

**Comment by chancedj** [comment]
np.  i just need to figure out what questID it is.

**Comment by magocchi** [comment]
Thanks chancedj!
Does this help? http://www.wowhead.com/quest=42897/daily-heroic-random-1st-legion

**Comment by chancedj** [comment]
thanks.  that should :).

**Comment by chancedj** [comment]
After more research i don't think that questId is the correct one for the essences.  I also finished heroic yesterday and it did not flag that a quest was completed so i wasn't able to trap the questId.  Wowhead doesn't have the current questId either from what i see so i'm stuck at the moment on this one.

**Comment by SacredDuckwhale** [comment]
This is an easy one. I've it in one of my own addons as well. What you want is...

1. The GetLFGDungeonRewards API - Not detailed on any Wiki as far as I can see, but the signature is:
 `doneToday, moneyBase, moneyVar, experienceBase, experienceVar, numRewards = GetLFGDungeonRewards(dungeonID)`
2. dungeonID see WowPedia entry:
> Number - This refers to a integer found in LFGDungeons.dbc. At the moment in build 25864 (7.3.5) the ID range is 1-1630 (integer).
3. The ID for the Daily Legion Heroic is 1046

All you need is the first parameter and you should be good. Obviously check for minimum level first, to be sure :)

**Comment by chancedj** [comment]
done!  code checked in.  thanks for the assist on the code.
