### ISSUE TITLE
research performance issue reported on forums

### ISSUE THREAD

**Issue by chancedj** [chancedj/LockedOut#115]
possibly related to event code that was added (firing too many times).  Will need to research and possibly refactor code.

**Comment by Daeveren** [comment]
Just out of curiosity, which forums are you talking about?

**Comment by chancedj** [comment]
curse project page.  should have said that instead of forums :).  i've noticed that there are a few times an event will fire multiple times back to back.  so i think i need to refactor some of the code so that it's not doing a full scan on every event which will help.

**Comment by Daeveren** [comment]
Oh right :) at first I thought the addon got its own website/forums and i didn't knew about it

**Comment by chancedj** [comment]
it looks like this might have to do with events - and possible data lookups (e.g. quest names and such).  will have to add this to some of the recoding coming up.  pushed to next milestone.

**Comment by chancedj** [comment]
this has not been mentioned anymore since the release so closing for now.
