### ISSUE TITLE
Error when hovering over raid lockout

### ISSUE THREAD

**Issue by truxtn** [chancedj/LockedOut#121]
This only started in 1.8.2  Let me know if there is any other information that would be useful

Message: Interface\AddOns\LockedOut\Minimap.lua:204: line number out of range: 14
Time: 05/21/18 14:04:11
Count: 2
Stack: Interface\AddOns\LockedOut\Minimap.lua:204: line number out of range: 14
Interface\SharedXML\SharedBasicControls.lua:208: in function <Interface\SharedXML\SharedBasicControls.lua:207>
[C]: ?
[C]: ?
...ce\AddOns\LockedOut\Libs\LibQTip-1.0\LibQTip-1.0.lua:1264: in function `SetCell'
Interface\AddOns\LockedOut\Minimap.lua:204: in function `displayTT'
Interface\AddOns\LockedOut\Minimap.lua:227: in function `_OnEnter_func'
...ce\AddOns\LockedOut\Libs\LibQTip-1.0\LibQTip-1.0.lua:1321: in function <...ce\AddOns\LockedOut\Libs\LibQTip-1.0\LibQTip-1.0.lua:1315>

Locals: errorMessage = "Interface\AddOns\LockedOut\Minimap.lua:204: line number out of range: 14"
DisplayMessageInternal = <function> defined @Interface\SharedXML\SharedBasicControls.lua:191
MESSAGE_TYPE_ERROR = 0

**Comment by chancedj** [comment]
thanks.  what dungeons/raids have you ran this week?  and have you ran any mythic+'s?

**Comment by truxtn** [comment]
might be easier for me to post a screenshot than list it.  https://imgur.com/a/Bm2zjyz
I have run +'s on the DH and Hunter, though I just realized it doesn't seem to show it.

**Comment by Hemario** [comment]
Seems to only occur on "Antorus" columns.
The other raids seem to be fine.

**Comment by Hemario** [comment]
I've been debugging into this a little further and I noticed the SavedVariables file has some unusual data.
["instances"].["Antorus, the Burning Throne"].["Lfr"].["bossData"] has in the thousands of items, where you would only suspect 11.

In Instances.lua in seems that _G.LFGLockList is not used and thus it adds those LFRs over and over again.
```
if( _G.LFGLockList and _G.LFGLockList[ tonumber(instanceID) ] == nil ) then
    populateBossData( instanceData.bossData, instanceID, numEncounters, difficulty, GetLFGDungeonEncounterInfo );
end
```
After deleting my savedvariables file and adding `_G.LFGLockList[ tonumber(instanceID) ] = true`, the issues is fixed. However, this does mean that you'll need to wipe the database to get the present data uncorrupted.

**Comment by chancedj** [comment]
thanks Hemario - i'll look into it what you're finding.  it might be a fix that i put in that should have been for keystones that is causing this.
