### ISSUE TITLE
errors in 8.0.1

### ISSUE THREAD

**Issue by Daeveren** [chancedj/LockedOut#132]
getting these errors at login:

`Message: Error loading Interface\AddOns\LockedOut\Libs\LibStub\LibStub.lua
Time: Thu Jul 26 17:37:49 2018
Count: 4`

`Message: Couldn't open Interface\AddOns\LockedOut\Libs\AceAddon-3.0\AceAddon-3.0.xml
Time: Thu Jul 26 17:37:49 2018
Count: 4`

`Message: Couldn't open Interface\AddOns\LockedOut\Libs\AceConsole-3.0\AceConsole-3.0.xml
Time: Thu Jul 26 17:37:49 2018
Count: 4`

`Message: Couldn't open Interface\AddOns\LockedOut\Libs\AceTimer-3.0\AceTimer-3.0.xml
Time: Thu Jul 26 17:37:49 2018
Count: 4`

`Message: Couldn't open Interface\AddOns\LockedOut\Libs\AceGUI-3.0\AceGUI-3.0.xml
Time: Thu Jul 26 17:37:49 2018
Count: 4`

`Message: Couldn't open Interface\AddOns\LockedOut\Libs\CallbackHandler-1.0\CallbackHandler-1.0\CallbackHandler-1.0.xml
Time: Thu Jul 26 17:37:49 2018
Count: 4`

`Message: Couldn't open Interface\AddOns\LockedOut\Libs\AceEvent-3.0\AceEvent-3.0.xml
Time: Thu Jul 26 17:37:49 2018
Count: 4`

`Message: Couldn't open Interface\AddOns\LockedOut\Libs\AceBucket-3.0\AceBucket-3.0.xml
Time: Thu Jul 26 17:37:49 2018
Count: 4`

`Message: Couldn't open Interface\AddOns\LockedOut\Libs\AceConfig-3.0\AceConfig-3.0.xml
Time: Thu Jul 26 17:37:49 2018
Count: 4`

`Message: Couldn't open Interface\AddOns\LockedOut\Libs\AceLocale-3.0\AceLocale-3.0.xml
Time: Thu Jul 26 17:37:49 2018
Count: 4`

`Message: Couldn't open Interface\AddOns\LockedOut\Libs\AceDB-3.0\AceDB-3.0.xml
Time: Thu Jul 26 17:37:49 2018
Count: 4`

`Message: Error loading Interface\AddOns\LockedOut\Libs\LibDataBroker-1.1\LibDataBroker-1.1.lua
Time: Thu Jul 26 17:37:49 2018
Count: 4`

`Message: Couldn't open Interface\AddOns\LockedOut\Libs\LibDBIcon-1.0\embeds.xml
Time: Thu Jul 26 17:37:49 2018
Count: 4`

`Message: Couldn't open Interface\AddOns\LockedOut\Libs\LibDBIcon-1.0\LibDBIcon-1.0\lib.xml
Time: Thu Jul 26 17:37:49 2018
Count: 4`

`Message: Couldn't open Interface\AddOns\LockedOut\Libs\LibQTip-1.0\lib.xml
Time: Thu Jul 26 17:37:49 2018
Count: 4`

**Comment by chancedj** [comment]
that's odd.  i have all those libs in the addon.  when i get home tonight i'll disable them all and enable just LO and see if it does the same.

**Comment by Daeveren** [comment]
Despite the errors. the addon seems to work without an issue. Also, these erros were each in a separate LUA error window.

**Comment by chancedj** [comment]
wierd.  i know that if other addons are loading those addons then it is already in memory and doesn't cause any issues.

Still, wierd.

**Comment by Daeveren** [comment]
Not sure if it's of any help, but here's a video recording of me going to all my 25 lua errors that show up at login (not all are related to LockedOut).
[2018-07-26_20-27-03.zip](https://github.com/chancedj/LockedOut/files/2232963/2018-07-26_20-27-03.zip)

**Comment by chancedj** [comment]
So i disabled everything (all addons) and am not getting the error.  Do you mind providing me a list of all addons you have enabled with that?  It looks like ElvUI is installled and possibly others?

**Comment by Daeveren** [comment]
Yes I do use ElvUI. My addons list is way too big to try anything lol.
Here's my list of addons enabled 
[2018-07-28_01-10-02.zip](https://github.com/chancedj/LockedOut/files/2237394/2018-07-28_01-10-02.zip)
But don't waste time with this. Unless others report same errors. It might very well be from other addons that will eventually get updated.

**Comment by chancedj** [comment]
yea. i'm thinking one of the  addons is causing this.  going to close - feel free to reopen if it persists.
