### ISSUE TITLE
Add option menu to configure options that we'd like to show or hide

### ISSUE THREAD

**Issue by chancedj** [chancedj/LockedOut#14]
As we begin to track more and more - the ability to have an option setting configured based on each char would be nice to have to control these settings.

**Comment by SacredDuckwhale** [comment]
I think you could use AceConfig to let users change settings, and AceDB to manage them more easily as well as implement the typical "profiles" interaction that is a de facto standard :)

I haven't really used AceConfig before, but I could look into it to get a basic GUI set up. That'll likely be useful for working with my own addons as well.

**Comment by chancedj** [comment]
Aceconfig is where i was probably going to go as it makes it easy to add a configuration menu.  If you want to tackle that i have no issues assigning the task to you. :)

**Comment by SacredDuckwhale** [comment]
I'm always busy, so I can't say if/when I'll have time. Also, the assigning is a bit awkward, it's likely intended to be used by project maintainers amongst themselves.

I'll just open a PR (before it is done, just to signal I am working on something) which can then serve as the place for discussion and reviews. As long as you self-assign (or mark things with a status:in-progress tag) there shouldn't be any overlap.

**Comment by chancedj** [comment]
thats fine.  don't worry about the PR right now as it will likely be the next thing i start since there are going to end up being some other issues likely gated behind it.
