### ISSUE TITLE
Track "Weekly Events"

### ISSUE THREAD

**Issue by smb** [chancedj/LockedOut#141]
Hi,

tracking for Weekly Events like Timewalking (do 5 Dungeons), World Quests (do 5 World Quests) etc. would be very helpful.

**Comment by chancedj** [comment]
thanks.  I had that last expansion, but i need to get all the questId's together again so i can get them tracked like before.  I'll see about adding them next release...either 1.8 or 1.9 - depending on if i have to update the questID for the world boss.

**Comment by chancedj** [comment]
done.  Will release tomorrow - after i verify the boss id is good!
