### ISSUE TITLE
toggle for instance limit

### ISSUE THREAD

**Issue by Daeveren** [chancedj/LockedOut#152]
Add a toggle for hiding the instance limit next to each character's name.
Ideally, the toggle would have 3 states: show for all tracked characters, show only for current character, hide all.

**Comment by chancedj** [comment]
adding as bug since i forgot to add the ability to turn on and off. will attempt to get it in 10.2

**Comment by Daeveren** [comment]
What about only showing for current char? Would that be doable?

**Comment by chancedj** [comment]
i think it should be doable.  i'll look into it and see.
