### ISSUE TITLE
error at login

### ISSUE THREAD

**Issue by Daeveren** [chancedj/LockedOut#160]
`Message: Interface\AddOns\LockedOut\Instances.lua:171: attempt to get length of local 'realmIdList' (a nil value)
Time: Sun May 12 17:53:13 2019
Count: 1
Stack: Interface\AddOns\LockedOut\Instances.lua:171: attempt to get length of local 'realmIdList' (a nil value)
...ce\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:583: in function <...ce\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:543>
(tail call): ?
Interface\AddOns\LockedOut\Instances.lua:171: in function `GetConnectedRealms'
Interface\AddOns\LockedOut\Instances.lua:268: in function `getLockDataByRealm'
Interface\AddOns\LockedOut\Instances.lua:308: in function `IncrementInstanceLockCount'
Interface\AddOns\LockedOut\Configuration.lua:632: in function `?'
...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:119: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[C]: ?
...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:29: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: in function `Fire'
Interface\AddOns\Ace3\AceEvent-3.0\AceEvent-3.0.lua:120: in function <Interface\AddOns\Ace3\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>`

**Comment by Daeveren** [comment]
And another error afterwards:
`Message: Interface\AddOns\LockedOut\Instances.lua:171: attempt to get length of local 'realmIdList' (a nil value)
Time: Sun May 12 17:55:34 2019
Count: 4
Stack: Interface\AddOns\LockedOut\Instances.lua:171: attempt to get length of local 'realmIdList' (a nil value)
...ce\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:583: in function <...ce\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:543>
(tail call): ?
Interface\AddOns\LockedOut\Instances.lua:171: in function `GetConnectedRealms'
Interface\AddOns\LockedOut\Instances.lua:268: in function `getLockDataByRealm'
Interface\AddOns\LockedOut\Instances.lua:308: in function `IncrementInstanceLockCount'
Interface\AddOns\LockedOut\Configuration.lua:632: in function `?'
...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:119: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[C]: ?
...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:29: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: in function `Fire'
Interface\AddOns\Ace3\AceEvent-3.0\AceEvent-3.0.lua:120: in function <Interface\AddOns\Ace3\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>`

**Comment by Daeveren** [comment]
Basically I was getting the Blizzard dialogue that addons are having many errors and prompted me if I want to disable them or ignore. Decided to enable the lua errors so I know which addons would spam. Proves out it's LockedOut, it keeps throwing the same error over and over if I keep the lua errors on. Here's how my lockouts look, maybe this would help figuring it out.

![wTwb4K664f](https://user-images.githubusercontent.com/6321337/57584028-77537d00-74df-11e9-999d-d448582d2869.png)

**Comment by chancedj** [comment]
thanks. this was reported on the forums, but i thought it would belimited to only the Chinese realms.  interesting.  I need to look at the code as i think i'm caching the result which would mean i'm likely caching the error.
