### ISSUE TITLE
BugSack capture

### ISSUE THREAD

**Issue by Jaladhjin** [chancedj/LockedOut#165]
58x LockedOut\Instances.lua:258: attempt to index field 'playerDb' (a nil value)
[string "@LockedOut\Instances.lua"]:258: in function <LockedOut\Instances.lua:257>
[string "@LockedOut\Instances.lua"]:355: in function <LockedOut\Instances.lua:344>
[string "=[C]"]: in function `ResetInstances'
[string "@(D) Auto Reset Instance\(D) Auto Reset Instance-8.2.5.lua"]:65: in function <...\(D) Auto Reset Instance\(D) Auto Reset Instance.lua:62>

Locals:
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'playerDb' (a nil value)"
addon = <table> {
 SetDefaultModuleLibraries = <function> defined @AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:367
 EnableModule = <function> defined @AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 IterateEmbeds = <function> defined @AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:442
 InitCharDB = <function> defined @LockedOut\Character.lua:139
 getQuestTitleByID = <function> defined @LockedOut\Helper.lua:362
 debug = <function> defined @LockedOut\Helper.lua:400
 Printf = <function> defined @AdiBags\libs\AceConsole-3.0\AceConsole-3.0.lua:69
 SetDefaultModulePrototype = <function> defined @AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:409
 getCharacterList = <function> defined @LockedOut\Helper.lua:458
 defaultModuleState = true
 IsEnabled = <function> defined @AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:451
 mergeTable = <function> defined @LockedOut\Helper.lua:559
 DisableModule = <function> defined @AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:350
 getConfigOptions = <function> defined @LockedOut\Configuration.lua:402
 Lockedout_BuildEmissary = <function> defined @LockedOut\Emissary.lua:58
 RegisterMessage = <function> defined @AdiBags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @AdiBags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 RegisterBucketEvent = <function> defined @LockedOut\Libs\AceBucket-3.0\AceBucket-3.0.lua:184
 EVENT_ResetExpiredData = <function> defined @LockedOut\Configuration.lua:683
 colorizeString = <function> defined @LockedOut\Helper.lua:406
 SetEnabledState = <function> defined @AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:424
 enabledState = true
 RegisterEvent = <function> defined @AdiBags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 Lockedout_RebuildAll = <function> defined @LockedOut\Character.lua:175
 IterateModules = <function> defined @AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:437
 checkExpiredLockouts = <function> defined @LockedOut\Character.lua:100
 Lockedout_BuildHolidayEventQuests = <function> defined @LockedOut\HolidayEvents.lua:184
 getCurrencyListMap = <function> defined @LockedOut\Helper.lua:484
 Lockedout_GetCommingEvents = <function> defined @LockedOut\HolidayEvents.lua:112
 getLockDataByChar = <function> defined @LockedOut\Instances.lua:269
 RegisterChatCommand = <function> defined @AdiBags\libs\AceConsole-3.0\AceConsole-3.0.lua:85
 UnregisterAllEvents = <function> defined @AdiBags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 printTable = <function> defined @LockedOut\Helper.lua:535
 OnInitialize = <function> defined @LockedOut\Configuration.lua:546
 NewModule = <function> defined @AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:235
 Lockedout_BuildWeeklyQuests = <function> defined @LockedOut\Quests.lua:86
 GetConnectedRealms = <function> defined @LockedOut\Instances.lua:172
 Lockedout_BuildCurrencyList = <function> defined @LockedOut\Currency.lua:85
 GetModule = <function> defined @AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:210
 ExpansionAbbr = <table> {
 }
 Lockedout_BuildInstanceLockout = <function> defined @LockedOut\Instances.lua:369
 ResetDefaults = <function> defined @Lock

**Comment by chancedj** [comment]
can you make sure you have the latest?  The stack trace you have is not aligning to any of the spots that would cause something like this.  strange.
