### ISSUE TITLE
serverResetDay does not line up with server reset - 1 day short

### ISSUE THREAD

**Issue by divinemaiden** [chancedj/LockedOut#167]
Hi! I've noticed that the LockedOut time remaining on the lockouts is not lining up with server reset and is essentially 1 day short

What I mean for this for example, Barthilas is on the US realm list but is on OCE time (GMT +10 with no DST right now). 

This means it is saying as of Monday 8.45pm server time is saying 4hrs and 15min remaining when truly that is incorrect as the Wednesday 1am server time which lines up with Tuesday 7am PDT announcement.

So it seems that it is out by 1 whole 24 hour window. 

Hopefully that makes sense.

**Comment by chancedj** [comment]
Thanks.  I thought i had resolved this a while back.  do the quest lockouts work fine (the daily ones)?  or do those seem off by an hour as well?

**Comment by divinemaiden** [comment]
After further inspection, it seems to be tied to world bosses only. I've moused over my mythic dungeons and raids and they show the correct time. Hope that helps further.

**Comment by chancedj** [comment]
thanks.  i'll check into it and see.

**Comment by chancedj** [comment]
This should be fixed now.  Blizzards gives us an api now to calculate this correctly.
