### ISSUE TITLE
Currencies tab is full of check boxes but no text

### ISSUE THREAD

**Issue by Racerx323** [chancedj/LockedOut#173]
The currencies tab is full of checkboxes but only a few on the very bottom of the list show an icon or text to signify what it is. I've tried clearing all settings for the add-on and removing and reinstalling. I also inquired on the Discord channel.

**Comment by Racerx323** [comment]
![2020-10-26_16-10-20](https://user-images.githubusercontent.com/6508113/97229200-f9079b00-17a5-11eb-81b9-11f8ec3ffd70.jpg)

**Comment by chancedj** [comment]
that's very strange.  normally it should gather that data again on re-open.  it sometimes has issues getting the data a first time from the server so returns blank.

I'll look into it this week.

**Comment by chancedj** [comment]
This is fixed with the latest release.
