### ISSUE TITLE
Open addon configuration/settings on right click

### ISSUE THREAD

**Issue by Daeveren** [chancedj/LockedOut#27]
Currently right clicking on the LO icon in a broker display (I use ChocolateBar) does nothing. It would be nice if it would open the addon configuration (this was the behavior on SI).

**Comment by chancedj** [comment]
This can probably be done with #14

**Comment by Daeveren** [comment]
Yes ofcourse, I should have posted it there. Suppose this can be closed then, or just leave it for tracking.

**Comment by chancedj** [comment]
Sorry, meant that the work can be done along with it :).  i hadn't considered how to bring up the options.

**Comment by chancedj** [comment]
done with release 1.4.1
