### ISSUE TITLE
Ability to change the addon icon on broker

### ISSUE THREAD

**Issue by Daeveren** [chancedj/LockedOut#28]
It would be nice if we could change between few other icons to show on the broker display. Currently LO uses an icon with a black background, which looks a little odd. Maybe consider even adding the SI icon, not sure it would create any issue or something.
Two examples of how it looks in my UI vs SI icon.

![2017-08-31 23_33_21-world of warcraft](https://user-images.githubusercontent.com/6321337/29944182-24e55f4c-8ea5-11e7-880f-2d9aa9a18bed.jpg)

![2017-08-31 23_33_28-world of warcraft](https://user-images.githubusercontent.com/6321337/29944193-29ef450c-8ea5-11e7-8b1b-555583116b68.jpg)

**Comment by chancedj** [comment]
Thanks.  I'll look into how to do this.  Any addons you have that allow the icon to be changed?

**Comment by Daeveren** [comment]
Can't think of one that would let you _chose_ the icon. Of the addons I have (that also have an icon on my broker display addon), Rarity changes its own icon automatically based on the item it tracks at that time. Rarity is an addon to keep track of your chances to loot rare items, such as boss kills/drops for mounts and stufff like this -- so for example once it detects that you're farming X mobs that have a pet as a drop, it would change its icon to that pet icon. It might be a too complex thing to implement a changing icon (vs the other feature the addon needs with a higher priority). Maybe consider doing something similar to SI? Not exactly same color or same shape, but something 'similar' in terms of look & feel. I guess even the current LO icon would work, if it had a transparent background (but not 100% sure, since the key/icon is predominantly white currently).

**Comment by chancedj** [comment]
actually, that's perfect.  as long as i have an addon that changes the icon out i can look to see how to make it update and refresh.  from there i just need to build a list of icons for people to choose from.  that helps.

**Comment by chancedj** [comment]
so i started to do this last night.  the problem i'm going to run into is that i can't give you any icon to choose from, i 'll have to limit the icons.  i attempted to get all the macro icons and it significantly bogs down the ui for config.  something about loading 2,100 icons in a dropdown list....:).

So if you want to provide about 20-25 wow cons from the interface\ dir, i could do that and limit to that list?

Also, from the looks of it i can't map the id back to a name and give someone the ability to search (limit) the returned icons.

**Comment by Daeveren** [comment]
Oh, when i created the issue i thought thought about using custom icons (as in: externally, outside of the game designed icons). But yes, I suppose there are some icons in the huge ingame selections that could fit. I'll have a look when I have some spare time and suggest some icons.

**Comment by Daeveren** [comment]
How to suggest icons here? Ok if I supply the icon ID? Problem is that wowhead no longer displays icon, something has to be breaked there http://www.wowhead.com/icon=237446/inv-scroll-11

**Comment by chancedj** [comment]
yea.  icon id is what blizzard has moved to.  they still use the texture location but nearly all (or at least most) of the api's were changed to stop returning the textture location and instead the id.

**Comment by Daeveren** [comment]
Right, so I got these as a first proposal
134244 (current one)
237446
1397630
132998
133278
1500867
133413
134245
132761
237284
237285
134532
237379
1508506
1516058
Let's see how they look ingame, in case any of them looks really odd it can get removed, of course. If additional ones can be added to the list, just let me know and I'll gladly have another go at it. Could probably pick even 100, but at that point not even sure how the addon will handle displaying them all in the selection window when you pick them.

**Comment by chancedj** [comment]
ok, thanks. a short list like that works for now :).

**Comment by chancedj** [comment]
ok! this is done too. thanks for the list.
