### ISSUE TITLE
Consider adding banded rows for easier reading

### ISSUE THREAD

**Issue by Daeveren** [chancedj/LockedOut#30]
Banded rows (the differently shaded rows, that are used in spreadsheets too) make it easier to read or actually track the info on a row, for multiple values. In wow addons, it's easier to follow a row (in LO's case say you're looking at Naxxramas lockout and on the line are your 10 alts as different rows). Eventually, with multiple columns, the data is going to be hard to 'track' on the screen, as our eyes move to other rows accidentally

Some examples:

![2017-09-01 00_13_07-world of warcraft](https://user-images.githubusercontent.com/6321337/29945679-d7cedb42-8eaa-11e7-8a38-fef29891ab4e.jpg)

![2017-09-01 00_13_30-world of warcraft](https://user-images.githubusercontent.com/6321337/29945685-e2727a7c-8eaa-11e7-9ded-70f23b5794dd.jpg)

**Comment by chancedj** [comment]
thanks.  will check into this.  possibly add for 1.4 or 1.5
