### ISSUE TITLE
color coded currencies

### ISSUE THREAD

**Issue by Daeveren** [chancedj/LockedOut#37]
Add color coded currencies that have a cap, example: green color to show when resource is not at cap, red to show when cap was reached. This would be a little tricky with current LockedOut implementation, since I see that each character's text (including the currency text of that char) matches that char's class color. So, for the purpose of this color coded suggestion, the text color for all currencties would have to become one color (white?) and not match the class color anymore.

![2017-09-30 11_46_35-world of warcraft](https://user-images.githubusercontent.com/6321337/31044333-e3f01e8a-a5d5-11e7-900f-f5f5e9ea83e9.jpg)

**Comment by chancedj** [comment]
completed.
