### ISSUE TITLE
currency: expansion sorted

### ISSUE THREAD

**Issue by Daeveren** [chancedj/LockedOut#38]
Add the option (or just make it default?) to sort the currencies by expansion.

In terms of visualizing the expansion of each currency, I'm not sure about the implementation. I see 3 options here:

1. Show no expansion name - just sort the currencies by expansion, without any visibile indication

2. Show the (shortened)  expansion name (grayed out) or the expansion icon/logo after the currency name
Example:
![lockedout](https://user-images.githubusercontent.com/6321337/31044456-51f7372c-a5d8-11e7-8c38-377ff7d63c88.png)

3. Show a divider/title with the expansion name. Personally I think this option would be the least desirable, since it would add many extra lines to the already big tooltip (with next xpac it's going to be 8 entries in the expansions list)

**Comment by chancedj** [comment]
it seems perhaps the preferred option is #2?

**Comment by Daeveren** [comment]
I'd myself preffer option 2 as well, forgot to mention.

**Comment by chancedj** [comment]
This one and #32 will likely be closed together.  going to finalize #37 first and once that is complete these 2 should be the last steps to release.
