### ISSUE TITLE
Add configuration options for which characters to show

### ISSUE THREAD

**Issue by Daeveren** [chancedj/LockedOut#40]
Add configuration options for which characters to show in the tooltip. It would make sense to have the list of chars in the configuration window sorted by realm and not alphabetically, it would be easier to deal with those that have same char name on multiple realms.

- [x] Add option to hide/show chars
- [x] Add option to show currently logged on char first
- [x] Add option to choose how to sort chars

**Comment by chancedj** [comment]
The list should be groupned (and sorted) by:

Realm first
Character name second.  I'll look into the other option though for choosing which to display.

**Comment by Daeveren** [comment]
Sorry I meant have worded it bad. I meant the list in the config window (not on the tooltip) to be sorted by realm, the one where you'd chose which chars to enable/disable. Reason for that was so you know which chars you'd disable incase you use same character name on 10 realms.
Currently there's no list of chars to enable/disable. The addon really needs a way to select which chars to show in the tooltip, because you'd log on say 20 chars for various reasons (bank accounts etc), but you'd only want to track your max lvl chars.

**Comment by chancedj** [comment]
ah ok, gotcha.  thanks.

**Comment by Daeveren** [comment]
Was just thinking, can't a temporary implementation until the full 'select your own chars to show' be just to... show only the characters that have the addon loaded? I currently have 14 chars in the (huge) tooltip and not sure how to make the list smaller.

**Comment by chancedj** [comment]
should we even be showing any chars < max level?  are you tracking things on those characters at all or are most people only worried about tracking max level chars?

**Comment by Daeveren** [comment]
I suppose several people have lower-than-max-lvl chars that they use for farming old content (like mounts). I myself have 8x lvl 110 and 4x lvl 100 chars that I use for various mount farming for a total of 12 chances for loot per week. Maybe other players have lvl 90 or even 80 that they use for farming. So in terms of what's the best level to do that, for me is 'hide all under 100', but for someone else the number might be different. Perhaps this would work as a band-aid fix until a proper enable/disable system is implemented. But long term, the min lvl implementation won't work, maybe someone wants to show his leveling char (say lvl 20), see what instances he done. There also has to be a way to delete a char from the database I suppose.

**Comment by chancedj** [comment]
ok.  there's not a lot to 1.6, so since i plan to get 1.5 out this week, i'll go ahead and leave the implementation of this to next version.  i have an idea on how to do this and the currency implementation should provid a good framework to be able to do this i think.

**Comment by Daeveren** [comment]
Excellent!

**Comment by Daeveren** [comment]
Hijacking this for 2 extra things that I think are linked.

1. A simple (but probably the most useful feature) checkmark of "always show currently logged character as first"; I really miss this from SavedInstances; if not, highlight the currently logged char in the list with some different column coloring, somehow.

2. Option to sort the chars. Like: 1. By name+realm; 2. By class; 3. Custom sort.
Not sure about #3 how doable it is, but if you're asking me, this would perhaps be the most useful of all 3, for those that have many chars (think of it like being able to sort the chars in the list just the way you have the chars sorted at the character login window).

**Comment by chancedj** [comment]
still need to implement the 2 other options you mentioned, but the first is done.  it's buggy only because i'm not creating/destroyng the options.  So if you remove a chars trakcing data then log back on that char it will not show until you reload.  but i just need to refactor some code to make that work.

We're getting there though :)

**Comment by chancedj** [comment]
also, modified your initial issue to add new trackable list so you know whats being worked on currently as part of this.

**Comment by chancedj** [comment]
last bug corrected, good to go now.
