### ISSUE TITLE
number shortening

### ISSUE THREAD

**Issue by Daeveren** [chancedj/LockedOut#41]
Add either number shortening (display 101.1k), either thousand separator, so that large numbers would be easier to read. Atleast for the resources that can go over 10k.

![2017-09-30 13_50_56-world of warcraft](https://user-images.githubusercontent.com/6321337/31045181-983d4600-a5e6-11e7-8f8c-b44a042cf507.jpg)

**Comment by chancedj** [comment]
this is done.  however it's not 100% as #42 was opened in hopes of fixing this.  however, i don't know that i can fix this without basically having everyone re-log on each char.  will investigate over the weekend.

**Comment by Daeveren** [comment]
I believe an assumption would be ok that everyone will log on their alts everyday for tradeskill CDs or every few days for various other things/weekly lockouts reset.
