### ISSUE TITLE
Argus - Inquisitor Meto tracking bug

### ISSUE THREAD

**Issue by Daeveren** [chancedj/LockedOut#43]
I've just noticed that LockedOut fails to track/show the correct chars that I have locked out on Inquisitor Meto world boss on Argus. I've killed the boss on 5 chars (which SavedInstances - pic 1 correctly tracks), but LockedOut only shows it on 3 chars (pic 2).
Note that I've had LockedOut enabled on all chars at the time of the kill yesterday and also I've relogged on each of the chars 2 times already and it still won't update the saves.

SavedInstances screenshot
![2017-10-01 20_37_08-world of warcraft](https://user-images.githubusercontent.com/6321337/31057287-050d3a76-a6e9-11e7-9972-aecc3310c4f3.jpg)

LockedOut screenshot (warrior - 1st column and mage - 3rd are incorrectly missing the kill)
![2017-10-01 20_37_35-world of warcraft](https://user-images.githubusercontent.com/6321337/31057288-082c7532-a6e9-11e7-8bb2-117c907b3cfa.jpg)

**Comment by chancedj** [comment]
thanks.  The argus invaision is a bit of a pain in the ass as the quests are not clearly defined - they're hidden, so it's not like before where we can just get the quest from wowhead.

when the boss is killed there are 2 questids flagged as complete.  i'm getting the other one and will post back when i have it.  Once i have it i'll see if you can run a script in your console to see if it shows complete for you.  it's possible that one is for the invasion point area and the other is for the boss and i just have the invasion point one and not the boss.

**Comment by chancedj** [comment]
run this please:

/run print(IsQuestFlaggedCompleted(49172));

if it returns true then i'll change the world boss quest id to that number

**Comment by Daeveren** [comment]
Just ran it, it returned false :(

**Comment by chancedj** [comment]
ok.  thats actually the one i have in my addon.  sorry, here's the other ID:

/run print(IsQuestFlaggedCompleted(49166));

**Comment by Daeveren** [comment]
this returns true :)

**Comment by chancedj** [comment]
ok!.  pushing a new version.  thanks for the help!

**Comment by Daeveren** [comment]
Anytime! I want this so bad to replace SavedInstances (which now is a resource hog due to various bugs), so I'm doing anything I try to help here. I have no programming skills, but can help with everything else, testing, suggestions, bug reporting etc.

**Comment by chancedj** [comment]
Thanks, i appreciate all the help.  the last month has been pretty hectic but trying to do my best to get new features in and not introduce bugs while doing so.
