### ISSUE TITLE
Add class hall quests

### ISSUE THREAD

**Issue by chancedj** [chancedj/LockedOut#45]

**Comment by chancedj** [comment]
i think for class hall quests, we're looking at tier 5 here, correct?

http://www.wowhead.com/order-hall-advancements-guide#advancements-tier-5

**Comment by Daeveren** [comment]
Yes, these ones
 Death Knight:  Frost Wyrm
 Demon Hunter:  Fel Hammer's Wrath
 Mage:  Might of Dalaran
 Paladin:  Grand Crusade
 Warlock:  Unleash Infernal
 Warrior:  Val'kyr Call

But afaik, these are not the quest names, these are only the researchable talents for the order halls. For mage, the daily WQ complete is Focusing Crystal (an item), which I see it's reward from Might of Dalaran quest (same name as above) but different spell ID 221602 http://www.wowhead.com/spell=221602/might-of-dalaran

**Comment by Daeveren** [comment]
So I see these have been introduced? I only have 3 chars with such insta-complete WQ abilities in their class halls: mage, warrior, DK. Warrior and DK are tracked OK, but the mage one is **not**

![wowscrnshot_102017_005336](https://user-images.githubusercontent.com/6321337/31796201-4d1e0574-b531-11e7-8992-c2b78043e371.jpg)

**Comment by chancedj** [comment]
Thanks.  I missed mage tracking.  I'll find the spell for it and put a new version out.

**Comment by chancedj** [comment]
looks like Warrior, DK and Warlock use the same spell.

Seems that paladins also have the same ability but i'm not having any luck finding the spell id.

http://www.wowhead.com/quest=44306/blessings-of-the-order

**Comment by chancedj** [comment]
btw, latest commit adds the quest.  if you want to pull down the file 'quests.lua" it should show now for mages.

**Comment by Daeveren** [comment]
It's quite broken, but can't figure out what exactly is wrong. At first it only shown 2 out of my 3 chars ticked. Then later on it only shows one out of 3.

**Comment by chancedj** [comment]
i branched for 1.6.0 and added the weekly dalaran quests. 

I'll check into getting the rest of these added as well.  I don't have all classes at 110, or even at 100 on some - so there are a few classes i won't be able to test.

**Comment by chancedj** [comment]
also, i added 3 more spell id's.  i guess i misread something thinking that the warlock/warrior were shared.  Let me know if that addresses the issues you're seeing.

**Comment by chancedj** [comment]
class hall quests done for instant complete.  will open other issues for any other missing class hall quests.

**Comment by Daeveren** [comment]
still issue with warrior not being tracked
