### ISSUE TITLE
Add setting to hide realm name

### ISSUE THREAD

**Issue by Daeveren** [chancedj/LockedOut#47]
Add setting to show/hide realm name.
Since currently it displays our chars like:

Realm Name
Character Name

I tend to quickly read the realm name for my chars instead their names so it gets confusing.

**Comment by chancedj** [comment]
there is an option to only show current current realm (characters only on the current realm).  how would you then show the realm if squashed to 1 line?  Or just show the name only at that point and not worry about the realm?

**Comment by Daeveren** [comment]
I know about that option, but I meant only showing character name (not display realm name). I have unique names for my chars on various realms. My goal is to have the tooltip have as few things possible (for easier readability) while still displaying the information I want.
SavedInstances has a ton of configurable stuff on everything, have a look in the 2nd pic.
I know the end-goal would be to completely replace SavedInstances, but due to SI having tons of configurable things, I guess that goal will take a lot of time (maybe years) until all that kind of configuration (not exactly the same, anyway) is made available in LockedOut. I'm here to point out the things I miss from my use case/my point of view, whether this is feasible, doable or what kind of priority would it be asigned that's all yours to decide :)


example from Saved Instances
![2017-10-04 09_49_20-world of warcraft](https://user-images.githubusercontent.com/6321337/31163103-78ac53c0-a8e9-11e7-9224-5e96739eefb8.png)

Saved Instances settings for displaying characters
![2017-10-04 09_51_00-world of warcraft](https://user-images.githubusercontent.com/6321337/31163137-9b333c38-a8e9-11e7-9a91-a3dd61cfe999.png)

**Comment by chancedj** [comment]
done.  realm name header is now configurable.
