### ISSUE TITLE
Character data not updating

### ISSUE THREAD

**Issue by Daeveren** [chancedj/LockedOut#48]
Using 1.5
Some of the data isn't populating. Even after logging on a char, if you don't mouseover LockedOut so it loads its tooltip, the data does not get updated.
Successfully confirmed it on my warrior. Logged on warrior without opening LockedOut tooltip and then logged on my paladin while opening the tooltip. The result is that for warrior it did not populate the emmisary data and also it did not update the currencies to the number shortening (k's). See picture below.

Also 2 small things that I suppose need to be addressed, thought I'd put them here instead of opening new issues for each of them, since it's related to 1.5.
1. add a space after the icon that is in front of the currency names, since now the icon is glued to the text :)
2. my opinion is that the current number shortening it's not quite the desirable one. I'd argue for using just one decimal, so just show 80.4k instead of 80.41k, easier to read and already that 0.4 is rather useless info as it is.  Then, 10.00k is not really shortening it, it's actually more chars than if it was showing the full 10000 number. Odd, right? Same for 100.00k vs 100000. Ideally these would be shown as 10k or 100k respectively. I'm not sure, but there might be some smart shortening code somewhere for addons to use, since I've seen it being used in many addons. For healthbars say it would smartly show 853, 11.5k or 12M, depending on how big the value is. So in a way, it does it in steps, under 1000 it shows the full number, above 1000 it shows like 1.1k, with one decimal, same up to 99.9k and after 100k it shows it as 105k, 173k (rounded up, no decimals) and the same for millions, 23M. I know this might be nitpicking, but simplifying the numbers being displayed makes them actually be readable in a table with tons of columns and 40 different currencies, as you can even see in the picture below.

![2017-10-03 23_32_36-world of warcraft](https://user-images.githubusercontent.com/6321337/31148342-1ea07496-a895-11e7-95d9-1e4b6b7b3069.jpg)

**Comment by chancedj** [comment]
yes.  this is part of another item.  i'll probably go ahead and implement the playerenterworld event at least for 1.5.0.

see issue #17 - right now the only way the addon gets updated is to hover over the tooltip.

**Comment by chancedj** [comment]
1) sounds good. i did add a space to the right, forgot about the left :)
2) sounds good.  will change to do 1 decimal position.

**Comment by chancedj** [comment]
Get the latest version.  it will now update on the login and boss kills.  i need to find more of the events, but at least it will be able to handle that part for you.  let me know if it's working better.
