### ISSUE TITLE
[Bug in 1.5] Missing character data

### ISSUE THREAD

**Issue by Daeveren** [chancedj/LockedOut#49]
On latest version of 1.5, it only shows the current logged character, everything else is hidden. Switching to another character makes it so only that char is displayed.

![2017-10-05 00_38_51-world of warcraft](https://user-images.githubusercontent.com/6321337/31200962-98ee26c8-a965-11e7-8399-5583cd5f9115.jpg)

**Comment by chancedj** [comment]
This actually exists in 1.4.0 - basically the way i have it written is it only shows data for boss and instances kills.  the rest shows with those.  i just need to fix that.  I've noticed it as well, just keep forgetting to get around and fix it :).  i'll do that with this release.

**Comment by chancedj** [comment]
ok, closed with latest push.
