### ISSUE TITLE
tooltip placement

### ISSUE THREAD

**Issue by Daeveren** [chancedj/LockedOut#51]
I know the addon is in heavy development, but I wanted to post about tooltip position inconsistency. If fixed by now it would probably make it easier to have it consistent with each future new features.

So the tooltip sometimes shows at the bottom of the screen, sometimes at the cursor. Not exactly sure myself about what the perfect implementation would be, but guessing that it'd be at the cursor (not glued to the cursor, but a little under it).

First 2 screenshots shows tooltip at the bottom of my screen.
3rd screenshot = tooltip at mouse cursor.
Also see the last screenshot for a formatting bug with text overlapping.

![2017-10-09 19_46_18-world of warcraft](https://user-images.githubusercontent.com/6321337/31349274-3efec324-ad2b-11e7-82b5-9e662c37a6c2.jpg)

![2017-10-09 19_46_28-world of warcraft](https://user-images.githubusercontent.com/6321337/31349276-3f03040c-ad2b-11e7-8b09-b8eaf8e85875.jpg)

![2017-10-09 19_46_35-world of warcraft](https://user-images.githubusercontent.com/6321337/31349277-3f039f70-ad2b-11e7-99e0-29ac295119dc.jpg)

![2017-10-09 19_50_49-world of warcraft](https://user-images.githubusercontent.com/6321337/31349275-3f008df8-ad2b-11e7-98c7-63aea572c45f.jpg)

**Comment by chancedj** [comment]
yea, what you're seeing happen there isn't really an issue with tt placement.  It's more the screen size.

you killed onyxia - 1 row.  but you cleared another instances that's 12+ and - while it's anchored to the bottom of the addon, it 's actually going to have a limit of the bottom off the screen, so it will push up into the overall tooltip and overlap.

what i need to do is remove the transparency from the hover tooltip and anchor it to the cell.  i should be able to do this as part of the next release.

**Comment by chancedj** [comment]
also, since the next release will let you configure the currencies, you should be able to hide the ones you no longer want to see which will make this better in the end.  But i'll go ahead and adjust where it anchors to.

**Comment by chancedj** [comment]
done with latest commit.
