### ISSUE TITLE
currency brackets 

### ISSUE THREAD

**Issue by Daeveren** [chancedj/LockedOut#52]
Running latest 1.5 commit (updated 3h ago), all the currencies show between bracket, not sure this is intended. Tried with both short and long currency format, same brackets.

![2017-10-11 11_48_45-world of warcraft](https://user-images.githubusercontent.com/6321337/31430701-5223780a-ae7a-11e7-9225-7d82ac6308d3.png)

**Comment by chancedj** [comment]
thanks.  this wasn't intended so i'll go ahead and fix that issue.  the missing currency is due to a format change in the old way i was storing it vs the new way.  the () should only be around the bonus rolls

**Comment by chancedj** [comment]
done!
