### ISSUE TITLE
Seal of broken fate

### ISSUE THREAD

**Issue by Daeveren** [chancedj/LockedOut#53]
Add mouse-over/tooltip info for the wekly seals. Currently it might display something like 2/6 (2). Upon mouse overing, it would display the 2 quests that have been turned in for the week. I think other means of Seal aquisition are also tied to quests, outside of these Dalaran ones (not sure myself, but there was a class order weekly quest that rewards a Seal?).

**Comment by chancedj** [comment]
yes.  certain classes have the class hall quest that allows it.

**Comment by chancedj** [comment]
will need the quests from here for this:

http://www.wowhead.com/currency=1273/seal-of-broken-fate#reward-from-q

**Comment by Daeveren** [comment]
Yes, those, but there are also some from order halls, just not sure how they're tracked, it seems they're not quests so can't be tracked then? (don't have this talent on either of my alts) 

Allows you to place a work order for 1 of your 3 weekly  Seal of Broken Fate in exchange for Order Resources.
 Demon Hunter:  Focused War Effort
 Druid:  Elune's Chosen
 Hunter:  Unseen Path
 Mage:  Arcane Divination
 Monk:  One with Destiny
 Paladin:  Holy Purpose
 Priest:  Blessed Seals
 Rogue:  Plunder
 Shaman:  Spirit Walk

from here http://www.wowhead.com/order-hall-advancements-guide#tier-5

**Comment by chancedj** [comment]
i believe they are spells.  if so,i have a way to track those as well.  i'll look into it a little more - thanks for providing the details :).

**Comment by chancedj** [comment]
Latest check-in adds class hall tracking for seal.
