### ISSUE TITLE
Track timewalking dungeons

### ISSUE THREAD

**Issue by Daeveren** [chancedj/LockedOut#61]
Any chance these could be tracked? They're technically not generating a lockout, but there should be a quest counter somewhere.

**Comment by Daeveren** [comment]
As an alternative, could atleast track the quest (which awards 500 timewalking badges) /script print(IsQuestFlaggedCompleted(40168)) - this would be really useful to know during timewalking (to track your alts that done it).

**Comment by chancedj** [comment]
Yup!  I'll add all the weekly from him..arena, time walking, etc :)

**Comment by chancedj** [comment]
All set :).
