### ISSUE TITLE
Resets clearing if cross realms

### ISSUE THREAD

**Issue by chancedj** [chancedj/LockedOut#63]
If you have characters on multiple realms, GetServerTime() returns the wrong time and could result in clearning out the characters too early.  Work on a fix to store the offset between ServerTime and Local Time so that the clearing happens properly.

**Comment by chancedj** [comment]
https://wow.gamepedia.com/API_GetQuestResetTime

problem may actually be with this function returning the "wrong" value.

proposed fix:  on char rebuild test return value.  if > 24 * 60 * 60, then exit and reattempt later.

**Comment by chancedj** [comment]
closed with latest commit.  testing happening in issue #67

**Comment by Daeveren** [comment]
Might have this still occuring. Running latest build (Latest commit bc2de3c  12 hours ago), my priest had cleared 1/11 Karazhan, yet the addon shows no lockout until i log him. It was same for my monk few mins before that (don't have screenshots for monk).
I have chars on 2 realms: Quel'Thalas (EU) (which is a merged realm) and Aerie Peak (EU)

![2017-11-03 14_26_49-world of warcraft](https://user-images.githubusercontent.com/6321337/32373783-a09531c8-c0a3-11e7-96cd-79d51a386e80.png)

![2017-11-03 14_28_21-world of warcraft](https://user-images.githubusercontent.com/6321337/32373785-a3c27b80-c0a3-11e7-90b9-56f25c1711ab.png)

**Comment by chancedj** [comment]
This one has to do with me changing the events around due to the instant reset complete.  I need to find the event fired when you're saved to an instance and it will correct this.  Before, player entering world always fired when going in and out of an instance - so when you leave the instance and log out it was resetting the addon and adding the karazan kills.

I was using the player entering world as a blanket way to "correct" the addon, so now i just need to get the correct ones added to fire. hopefully that makes sense.

**Comment by Daeveren** [comment]
Why wouldn't the addon just write to the database at the time of a lock/save (boss/dungeon/quest etc) and then only access it from cache until expiry? (or atleast hardcode a reset/resync with server every week on restet day)

**Comment by chancedj** [comment]
yes.  thats the plan :).  that's what i meant by that.  before i was using the player login event as a blanket fix because i didn't subscribe to the events.  i just need to find the event that's fired when you're saved to an instance and that should be corrected.

**Comment by chancedj** [comment]
ok.  latest checkin should now rebuild for when a raid or instance boss kill ends successfully.

**Comment by Daeveren** [comment]
This issue still happens. Latest 1.6 build. Just logged out from warlock Viesse (who just killed 1st boss in Karazhan), it was shown on LockedOut when I was on Viesse. Now switching chars on Diessen (on same realm - Aerie Peak EU) shows no save for Viesse anymore. Also Jaesse (on same realm) has killed 1st boss in Karazhan earlier today, is missing in the photo.

![2017-11-08 11_25_00-world of warcraft](https://user-images.githubusercontent.com/6321337/32541292-f27ea762-c477-11e7-94d7-63dcd627bb0b.png)

after logging on Jaesse
![2017-11-08 11_27_56-world of warcraft](https://user-images.githubusercontent.com/6321337/32541305-fa15115a-c477-11e7-90a0-ad630d3ca8f1.png)

**Comment by chancedj** [comment]
i'll reopen.  i'm still not seeing the issue happen but will keep it open for a while to see if there's a pattern.  i'm just about ready to release and i think we're good without this being fixed as it's really hard to track down atm.

Might have to enable debugging and see if i can get a printout from you with it enabled.

**Comment by Daeveren** [comment]
Sure, enable debugging for beta.
Would it be complicated to add a toggle for debugging?

**Comment by chancedj** [comment]
nope.  shouldn't be difficult.  what i'll have to do is probably stuff it all into an array then spit it out later.  there are times as the ui is getting it's stuff together that i can't print to the chat window.  so i would stuff to the variable then loop when the ui is ready and send it to the chat window.

It's a really odd bug you're seeing.  hopefully with the debug statements we can get to the bottom of it.

**Comment by chancedj** [comment]
As part of the fix for #70 - i'm going to rewrite this code and hope it corrects the issue with 1.7.0.
