### ISSUE TITLE
warrior instant not tracked

### ISSUE THREAD

**Issue by Daeveren** [chancedj/LockedOut#66]
warrior class hall daily WQ complete not tracked properly

**Comment by chancedj** [comment]
I just did it and it is showing for me.  odd?

![warrior instant](https://user-images.githubusercontent.com/30790056/32200687-4faa2c70-bda9-11e7-9a7f-af2031fb9adb.PNG)

**Comment by Daeveren** [comment]
just checked it now after logging on the warrior and then onto another character and it is showing up; 1h ago it was not showing up, even tho i did used the quest item several hours ago - meanwhile i changed to the newest beta build and deleted my game cache folder, but not quite sure either of these affected it in any way.

**Comment by chancedj** [comment]
ok.  i'll close for now.  i just made another push to add the free quest seal tracking and also added the seal tracking to the weekly quests (under instant complete).
