### ISSUE TITLE
class hall instant WQ

### ISSUE THREAD

**Issue by Daeveren** [chancedj/LockedOut#67]
This thing seems to be completely broken, somehow. Can't figure where it starts hiding stuff.
Using build from 30 oct, just now realized it's not the most recent, will test tomorrow with the newest version too.

Steps:
1. I'm on one of my non-instantWQ alts. At that point, I notice that no instant is ticked in LockedOut; already completed like 1h before, on mage and on DK.
![2017-10-31 19_36_02-world of warcraft](https://user-images.githubusercontent.com/6321337/32239680-df9e50a2-be73-11e7-94da-63eb02053fa6.jpg)

2. I log on my warrior to complete the instant WQ. When I log him, still no instant complete is showing up, when I use the warrior's order hall item to complete a WQ it gets ticked on LockedOut (but still no signs of the mage and DK).
![2017-10-31 19_37_36-world of warcraft](https://user-images.githubusercontent.com/6321337/32239725-079eb614-be74-11e7-9c11-257795dc7a67.jpg)

3. I log on my DK (and not do anything) - the tick on LockedOut pops up.
![2017-10-31 19_39_24-world of warcraft](https://user-images.githubusercontent.com/6321337/32239888-79790ee2-be74-11e7-9229-5170c854e6a8.jpg)

4. I log on mage too, now LockedOut shows all 3 instant completes.
![2017-10-31 19_41_09-world of warcraft](https://user-images.githubusercontent.com/6321337/32239905-88bbf8ec-be74-11e7-9ac6-4f3c1f50b6b9.jpg)

**Comment by chancedj** [comment]
did you do the instant quest on the mage and DK and verify it was checked before going?  It's possible that i'm not trapping the correct event - so at that point it would not register that the class hall quest (spell) is fired.

so basically did you do the following steps:

log on mage
complete wq
log off
log on dk
complete wq
log off
log on warrior
complete wq
view lockedout
log off
...mage...
...dk...

right now there are 2 places i'm testing events.

1. player login
2. quest complete

**Comment by chancedj** [comment]
btw, sometimes this might be easier over b.net - feel free to add me if you want.

Stinkfist#1929

**Comment by Daeveren** [comment]
Added you, not sure it worked, got no confirmation. I'm from EU, maybe that's why?

**Comment by chancedj** [comment]
hmm. maybe.  i'll research later tonight. i think i have a solution to the problem though - will check something in later tonight probably.

**Comment by chancedj** [comment]
Latest check-in should fix this.  steps to test:

- log in
- perform world quest
- log out
- log on separate character.
- check display to see if it's logged as completed.

**Comment by Daeveren** [comment]
Forgot to clearly look at the tooltips today, will try again tomorrow. Only noticed that DK was still *not* showing up in the tooltip, despite having the instant WQ completed (once I logged him, it showed up).

**Comment by chancedj** [comment]
i have a warrior and warlock.  i'll give it a shot here soon :)

**Comment by chancedj** [comment]
ok.  tested with the event and didn't work.  attempting a new event and will test tomorrow.  if all works ok, will close out.  this one is starting to become a pain in the ass!

**Comment by Daeveren** [comment]
Will test in about 1h and see how it goes. Meanwhile, I noticed this happens pretty often

![2017-11-02 14_30_19-world of warcraft](https://user-images.githubusercontent.com/6321337/32326166-8644797e-bfda-11e7-8aa9-eed34b3271f6.png)

![2017-11-02 14_30_35-world of warcraft](https://user-images.githubusercontent.com/6321337/32326171-89990022-bfda-11e7-97c7-01b1afbe3a0f.png)

**Comment by chancedj** [comment]
49 days?  Wierd...looks almost like it set a wrong reset data.  i've never seen that one happen ugh.

**Comment by Daeveren** [comment]
Kept looking at the tooltip today, I've done the instant WQ on 4 chars, I kept looking one after one, it saved properly. I switched chars several times, it all was fine. Until now when I logged on my main and all of a sudden the warrior instant is gone!

![2017-11-01 21_36_44-world of warcraft](https://user-images.githubusercontent.com/6321337/32352443-f123860a-c029-11e7-93ed-1bf2e3ca1f9d.jpg)
![2017-11-01 21_56_42-world of warcraft](https://user-images.githubusercontent.com/6321337/32352446-f52ec8ae-c029-11e7-8a72-aa02e02eebf4.jpg)
![2017-11-02 23_56_14-world of warcraft](https://user-images.githubusercontent.com/6321337/32352456-f9dcfb1e-c029-11e7-9afe-458a0b6c3dfe.jpg)

**Comment by chancedj** [comment]
ok, i can reproduce this now.  it seems that refreshing based on player_entering_world might not be the best idea.  i might have to consider another method.

It seems the spell is not ready when you enter the world (same event fires in /rl but you're techincally in then).

I believe this is a similar issue to the one i was seeing with the pet charms.  if you want a sec and open the screen the instant quest WILL show.  so i may need to find a better event or refactor some code.

**Comment by chancedj** [comment]
ok! I believe i have a fix in place.  will test it out.  should be something that if you log in all your chars and get the data it should always show now.  right now i'm only clearing the e xpired data on login.  I'll need 1 more event to hook to an i think i can close this out completely.  give it a shot

**Comment by Daeveren** [comment]
Can't you add like a 10-20 sec delay until the data is read?

**Comment by chancedj** [comment]
yes.  i could probably do something along those lines.  part of what i write is just to give a lot of information on why it's happening so the addon has a good trail of documentation on bug fixes and why i did things a certain way.

**Comment by chancedj** [comment]
Fix is tested and we're good to go on this now :)
