### ISSUE TITLE
possible debug chat left enabled by default

### ISSUE THREAD

**Issue by Daeveren** [chancedj/LockedOut#69]
Is this from LockedOut?
Seems debug code enabled from some addon, but there's no way for me to figure which addon might do it. It only started showing up yesterday.

![2017-11-03 12_20_24-world of warcraft](https://user-images.githubusercontent.com/6321337/32369347-84be2930-c091-11e7-9012-23be211843c9.png)

**Comment by chancedj** [comment]
yes.  thats from my addon.  it was checked in after i fixed the world quest problem :).  so i'll go ahead and remove it here shortly.

**Comment by chancedj** [comment]
there.  fixed :)
