### ISSUE TITLE
Anniversary event world bosses

### ISSUE THREAD

**Issue by Daeveren** [chancedj/LockedOut#78]
Using 1.7, commit commit 8e85663.
Killed Kazzak yesterday (when LockedOut didn't had support for anniversary event). Today I got the above version of the addon and killed Kazzak again. Still no boss is shown as tracked/killed.

Also, is there a way to display which of the bosses are up during this event? Like it shows which Legion world boss is up even if you didn't killed it yet.

**Comment by chancedj** [comment]
yes.  i have support for just the quests atm.but didn't think of the bosses.  But i plan to add those today and get another release out.

**Comment by chancedj** [comment]
I added the bosses. It seems that sometimes the boss tracking DOES work (to show the ones that aren't dead yet).  and sometimes it doesn't.  in this instance it doesn't work and i don't want to make too many changes to force it to work.

**Comment by Daeveren** [comment]
They use a mixed system. Kazzak and Azuregos are always up. As for the 4 dragons, only one of them is up at a time, then it rotates (I believe it's daily rotation). Anyway, kill tracking should do the trick.

**Comment by chancedj** [comment]
because it's only a short period and i haven't forked 1.7 yet. :)

**Comment by Daeveren** [comment]
Oh right. I've moved to 1.6 release for Anniversary event tracking, when 1.7 beta gets this feature I'll get back to the testing version.

**Comment by chancedj** [comment]
yea.  there haven't been any changes to 1.7 so i think i'm going to kill that branch and create it again.  i'm out for a week, so i'll start work on it when i get back!

**Comment by Daeveren** [comment]
timer is wrong btw, they anniversary bosses reset daily

**Comment by chancedj** [comment]
Can you do a practice and fix it?  I'm out of town and can't fix it on the phone but I can commit a PR on the phone :)

**Comment by Daeveren** [comment]
I have looked in the worldboss.lua file but I have no clue where the lockout timer is, in the file.

**Comment by chancedj** [comment]
Yeah. I just realized I would have to change the table and the code to reflect that the bosses are weekly vs daily :/.

**Comment by chancedj** [comment]
Checked in from my phone.  Can you grab the world bosses file and see if it's fixed?

**Comment by chancedj** [comment]
Ok. Just pushed the change as release 1.6.8

**Comment by Daeveren** [comment]
There, writing wow addons from the phone #herooftheday
