### ISSUE TITLE
multi-realm data not displayed properly

### ISSUE THREAD

**Issue by Daeveren** [chancedj/LockedOut#82]
The data for my chars on my 2nd realm is still acting in the way as "sometimes is not showing up". I notice it for Karazhan, screenshots attached.

First it shows Jaesse does not have a Karazhan save (even tho I'm fairly sure I did it on that char too)
![2017-11-19 23_57_08-world of warcraft](https://user-images.githubusercontent.com/6321337/32996025-e3d3fe1c-cd85-11e7-9b53-c0489fcf7121.jpg)

Logging on Jaesse makes the Karazhan save show up
![2017-11-19 23_59_32-world of warcraft](https://user-images.githubusercontent.com/6321337/32996037-fe7b6890-cd85-11e7-9469-53fd5660fb89.jpg)

**Comment by Daeveren** [comment]
Also, again the Instant Complete data is acting funky, not showing the checkmarks. Might be related to this same issue or something.

On my main, Daeveren, I see that Diesse and Diessen don't have the Instant Complete
![2017-11-20 22_06_03-world of warcraft](https://user-images.githubusercontent.com/6321337/33039080-7bcc1f9c-ce3f-11e7-83d9-0294abd4a76d.jpg)

Logging on Diesse makes the checkmark show up
![2017-11-20 22_07_02-world of warcraft](https://user-images.githubusercontent.com/6321337/33039177-cdc0a624-ce3f-11e7-8613-06a23c935ed6.jpg)

Logging on Diessen makes his checkmark show up too
![2017-11-20 22_08_29-world of warcraft](https://user-images.githubusercontent.com/6321337/33039207-dfe32e62-ce3f-11e7-9e5d-6526cc157712.jpg)

**Comment by chancedj** [comment]
do you know if any of these are on separate time zones?

**Comment by Daeveren** [comment]
No clue about the actual timezones. Both servers are on EN-EU. I could only find this old list on WoWWiki http://wowwiki.wikia.com/wiki/EU_realm_list_by_datacenter
That's from back when the realms were in different battlegroups, I have no clue if they still run like that now.

**Comment by chancedj** [comment]
ok, thanks.  I believe i have a bug with my weekly lockout function.  I'll be working on writing up a test case to test it out and make sure it's calculating correctly.  I really wish blizzard would make a function to show when the server reset will happen as well.

**Comment by Daeveren** [comment]
Isn't already a function that shows when the lockout expires? At least for the raids that aret racked in the default ingame raid lockout tracker.

**Comment by chancedj** [comment]
in some places yes, but not always.  i just need to look it over again is all.

**Comment by chancedj** [comment]
for more information see this function:

https://github.com/chancedj/LockedOut/blob/master/Instances.lua#L102

there are 2 loops. 

1. this one gets the Raid finder dungeons - i have to calculate a reset date for that one. ( https://github.com/chancedj/LockedOut/blob/master/Instances.lua#L106 )
2. this one gets the Saved Instances - i can use the reset date returned from that one. ( https://github.com/chancedj/LockedOut/blob/master/Instances.lua#L121 )

**Comment by Daeveren** [comment]
unfortunately the dungeon tracking still doesn't work consistently

here i'm noticing that **some** of my chars on my 2nd realm (Aerie Peak EU, my main realm is Quel'Thalas EU), namely Diessen and Viesse are missing one of the 2 dungeons I ran today on several chars (I've ran Stonecore and Zul'Gurub, mount runs)
![2017-12-11 18_28_35-world of warcraft](https://user-images.githubusercontent.com/6321337/33841927-be377a30-dea1-11e7-90a0-8f6f493eeefb.png)

after I log on Diessen, his dungeon save appears
![2017-12-11 18_29_23-world of warcraft](https://user-images.githubusercontent.com/6321337/33841944-c8313648-dea1-11e7-8411-dc6f2ffc6d81.png)

same for Viesse
![2017-12-11 18_30_20-world of warcraft](https://user-images.githubusercontent.com/6321337/33841946-ccb8a5ca-dea1-11e7-8004-fd678527cae5.png)

odd thing is that Daevea and Jaesse are on 2nd realm too and their saves is shown correctly

**Comment by chancedj** [comment]
ok - good.  ithink this is a matter of being saved to the instance but the api not being ready yet to let you know you're saved. ( hovering over teh icon after exiting the instance may fix that).  I'll do a little more investigation - however this should be something that when it IS tracked it shouldn't just randomly disappear anymore.

I'll open up a new issue for this so it has a better title.

**Comment by chancedj** [comment]
opened under issue #91

**Comment by chancedj** [comment]
this was fixed under #91 - but just checking up to see if you've noticed the issue anymore or if everything looks good now.

**Comment by Daeveren** [comment]
Well, I'm done with farming Karazhan on all my alts (got the mount lol), but hopefuly I find something else to farm on multiple chars. Will see how much time I have for this, with the holidays coming. Be sure that I'll come here and update once I find something :)
