### ISSUE TITLE
Enhancement: cheap Argus troops

### ISSUE THREAD

**Issue by Aspin-KT** [chancedj/LockedOut#88]
Please add tracking for the cheap Argus troops.  The first quest each week is only 150 resources, vs. the 900 from the unlimited repeatable quests.

The quests are:

http://www.wowhead.com/quest=48910/supplying-krokuun
http://www.wowhead.com/quest=48911/void-inoculation
http://www.wowhead.com/quest=48912/supplying-the-antoran-campaign

I can add them manually to Quests.lua (line 106) with:

```
	["cheapridgestalker"]   = {name=L["Argus - Cheap Ridgestalker"],    startNdx=1, endNdx=1, resetForm="weekly", checkStatus=checkQuestStatus, copyAccountWide=false, checkIDs={48910} },
	["cheapvoidpurged"]     = {name=L["Argus - Cheap Void-Purged"],     startNdx=1, endNdx=1, resetForm="weekly", checkStatus=checkQuestStatus, copyAccountWide=false, checkIDs={48911} },
	["cheaplightforged"]    = {name=L["Argus - Cheap Lightforged"],     startNdx=1, endNdx=1, resetForm="weekly", checkStatus=checkQuestStatus, copyAccountWide=false, checkIDs={48912} },
```

They don't appear in order or grouped together though, so there's probably some better way!

**Comment by chancedj** [comment]
thanks for putting it all together.  i can either leave it assigned to me, or assign it to you if you want to do a PR and add them in yourself.

Either way, i 'll see about getting them into 1.7.x (next release)
