### ISSUE TITLE
Track Holiday Events

### ISSUE THREAD

**Issue by Daeveren** [chancedj/LockedOut#93]
Add tracking for Winter Veil dailies that people usually do on multiple chars: the 4 dailies at garrison and the ones in Ironforge/horde equivalent

**Comment by chancedj** [comment]
thanks.  I'll check into this.

**Comment by Daeveren** [comment]
Correct

**Comment by chancedj** [comment]
with everything going on, i'm not sure i'll be able to get to this in time to make it useful.  however, i'll create a holiday module with the next release likely and put everything in there for winter veil and whatever other holidays going on.

**Comment by Daeveren** [comment]
Happy holidays! Sure. Hopefuly I'll be here next year at this time for testing :)
